### ISSUE TITLE
Import schema for data types

### ISSUE THREAD

**Issue by jasloe** [dramonline/soundamerican#1]
I've sent a shared Google Drive invitation to you containing the schema documentation.

These include the following content data types:
```
Article
Person
```
And the following taxonomy data types:
```
Role
Instrument
```
## Person
Required fields for Person include:
```
title
fname
lname
role
```
I've included two example records for John Cage and Josh Sinton. 

Fields with multiple values should be semi-colon delimited, e.g.:

```
composer;musician;writer
```
## Article
Required fields for Article include:
```
title
author
issue
```
Though Cage is not an explicit contributor to SA, we likely want to attach his identity to articles where his work is discussed. Other examples include Steve Lacy, Terry Riley, Edgard Varèse, etc. Again, not contributors per se to the publication but they are featured in articles. Use ```related_people``` to associate a ```Person``` record to an ```Article```.

### Instrument, Role
This schema is self-documenting. These values refer to values in Article and Person. One value per row.

**Comment by natewooley** [comment]
Just did the author title fields for SA21. If you have a moment can you just check my methodology and make sure it's being entered as you need it? Tomorrow I can start putting in SA22 and then move to the archived issues. Thanks!

**Comment by jasloe** [comment]
Looks good. This is a great start. No changes needed. 

We'll need data for the "Person" data type in order for the articles to connect to the people named in each issue. 

https://docs.google.com/spreadsheets/d/1_uvmD9pKDpxAcU_7Qnej2nJ57FS2_HtL7zGnAycXKKk/edit?usp=sharing

**Comment by natewooley** [comment]
I finished the article titles and authors in the google doc today. That should be up to date through SA22. I think I'll be able to get to the rest of the spreadsheets next week and get those populated by Friday.

**Comment by jasloe** [comment]
Ok. I'll get those imported over the weekend. I have a shortcut to get the people spreadsheet started that'll save some time. I'll let you know when that's on its way.

**Comment by jasloe** [comment]
@natewooley – I parsed the content in columns E and F and dumped them into the [Person schemaI w table](https://docs.google.com/spreadsheets/d/1_uvmD9pKDpxAcU_7Qnej2nJ57FS2_HtL7zGnAycXKKk/edit#gid=700135632).

I went ahead and imported this content, along with the articles and issue "stubs". We can further enrich the people content (e.g. biographical note, links to person's webpage, birth/death dates, etc.) in the admin interface or by populating and running the spreadsheet importer again. 

I'll push the entire corpus to development by tomorrow afternoon.

**Comment by jasloe** [comment]
@natewooley -- ok, all content has been migrated from spreadsheets to the site. Didn't throw any errors. I recommend spot checking a couple dozen articles to make sure everything lines up. 

Go to: http://dev.soundamerican.org/admin/content

Then select "Article" under the Content Type select list to view all articles. I'm going to close this issue and start working on a workflow to copy body copy and interview copy into the site.  


```
 ------------------- ------------------------------- -------- ------- ---------- ------------- ---------------------
  Group               Migration ID                    Status   Total   Imported   Unprocessed   Last Imported
 ------------------- ------------------------------- -------- ------- ---------- ------------- ---------------------
  nodes (nodes)       articles                        Idle     262     262        0             2019-06-11 12:27:52
  nodes (nodes)       issues                          Idle     23      23         0             2019-06-10 22:18:23
  nodes (nodes)       organizations                   Idle     24      24         0             2019-06-11 12:30:07
  nodes (nodes)       person                          Idle     357     357        0             2019-06-10 22:41:10
```
