### ISSUE TITLE
Wheeler endnotes

### ISSUE THREAD

**Issue by jasloe** [dramonline/soundamerican#15]

**Comment by jasloe** [comment]
@natewooley –– This is fixed. Will push tonight. 

I wonder if the footnote copy should appear closer to their respective reference? So that users don't have to scroll to the bottom of the screen to read the note.

**Comment by natewooley** [comment]
We use the endnotes in the print version, which is why I was thinking of them as occupying the same space here. In the past, I inserted anchors to bounce back and forth, but maybe that's too clunky a solution?

**Comment by jasloe** [comment]
How about side notes?

Scroll down to "sidenotes": https://edwardtufte.github.io/tufte-css/
