### ISSUE TITLE
About the Author headshots -- missing

### ISSUE THREAD

**Issue by jasloe** [dramonline/soundamerican#17]
Fisher-Lockhead, Rakowski, needs photo of Chris in about author

**Comment by jasloe** [comment]
@natewooley –– Can you check and make sure these are loading?

http://dev.soundamerican.org/issues/hyla/hyla-lick-maneuvers
http://dev.soundamerican.org/issues/hyla/composing-spontaneity-lee-hyla-and-score-field-action

**Comment by natewooley** [comment]
both loading for me

**Comment by jasloe** [comment]
Cool. Closed.
