### ISSUE TITLE
Categorizing content

### ISSUE THREAD

**Issue by jasloe** [dramonline/soundamerican#28]
@natewooley 
@lkahlden 

I plan on categorizing content into a few different thematic lists. Not sure how the UI will work at this point but the idea is that we have lists compiling the following:

- Editor's notes
- Sites of Formations
- Interviews
- A Bunch of People Doing Something
- Exquisite Corpses (two, to date) 
- Any others?

Interviews are easy enough to track down. 

Nate, how far back do the SoF and Bunch go back?

**Comment by natewooley** [comment]
Hey Jason,

SoF, exquisite corpse, and bunch of people doing things have only occurred in issues 21 and 22

**Comment by jasloe** [comment]
Ok, good to know, thank you.
