### ISSUE TITLE
Question about role attribution in schema-person

### ISSUE THREAD

**Issue by natewooley** [dramonline/soundamerican#4]
I'm entering roles and other info into this spreadsheet today and had a question about how we attribute the roles to people. Contributor is there and makes sense, but does that count for people that were the subject of an interview or should we try and create a different term for that. As for the people mentioned in articles but who don't count as 'contributors', such as Charles Mingus, Baudrillard, etc., what terminology would you prefer I use for them: Mentions? Subjects?

**Comment by jasloe** [comment]
Subject, I think, is appropriate.

**Comment by natewooley** [comment]
okay, I'm still feeling sick so I'm going to head home but I got the instrument roles put together. I think we should talk next week about the actual roles (contributor, subject, etc) because there are a lot of fine gradations and I want to make sure I have a methodology in place to get them right.

**Comment by jasloe** [comment]
No problem. I'm working on some subtle, tasteful page transition animations and other typographic nuances to give the site a bit of sparkle. It's coming together!
